### ISSUE TITLE
Restrictions needed for adding classes to the workspace

### ISSUE THREAD

**Issue by leon-k-martin** [the-virtual-brain/tvb-ext-ontology#1]
Currently, there are no restrictions on the types of classes that can be added to the workspace. For example, I can assign *PostsynapticPotential* to `Connectivity`. The `Connectivity` field should only accept classes with it as a parent. 
This issue can lead to improper class associations and potential errors in the workspace.

**Comment by romina1601** [comment]
hi @leon-k-martin 
we do have restrictions here: https://github.com/the-virtual-brain/tvb-ext-ontology/blob/d2f9d6ae5103bdd7ebfca363fd0c6de9c33985fd/src/App.tsx#L24
where we use the "type" attribute of a node to check if it can be added to the workspace. For connectivity, could you indicate what type should the nodes have to be allowed in the workspace? And can you give me some examples of connectivities from the ontology?

**Comment by leon-k-martin** [comment]
Great, thanks!

For the Connectivity, I think we'd need two Options:
1. Select parcellation and normative tractogram from the Ontology: The Connectivity object is instantiated with average data with the desired network. The following tasks are needed
    - [ ] Update ontology with parcellations
    - [ ] Integration with tvbo-data to load matrices.

3. Upload your own weights and length matrices.

What do you think?

**Comment by romina1601** [comment]
1. Sounds good. Does the current ontology have any normative tractogram nodes? Also, I would have preferred for the user to select just one node for each case. I understand that for connectivities 2 nodes will be needed, right? We need to make sure that the users know this. 
2. I agree, this should be straightforward for the users to understand.

**Comment by leon-k-martin** [comment]
1. For now, maybe let's make it simple and provide an option for selecting the parcellation for a normative SC without selecting the Tractogram (We only use one, so others can be added later).  What do you say?

**Comment by romina1601** [comment]
1. Sounds good 👍🏻 so for the moment I will disable adding any nodes to the Connectivity field from Workspace
