### ISSUE TITLE
Graph View Window Size Too Large

### ISSUE THREAD

**Issue by leon-k-martin** [the-virtual-brain/tvb-ext-ontology#2]
Description:
The graph view window does not resize flexibly, leading to issues where results are sometimes displayed outside of the visible area. This forces users to scroll, which is not ideal for usability.

Proposed solution:
Arrange windows of fixed size and constantly adjust content to fit in. Maybe implement the zoom-in function to show the graph with the optimal viewpoint.

**Comment by romina1601** [comment]
Hi @leon-k-martin 
could you test it now and maybe attach a screenshot if the problem is still there?

**Comment by leon-k-martin** [comment]
Works now, closing now since issue #3 covers the enhancement part of this issue. :)
